Update mount

diff --git a/mount b/mount
--- a/mount
+++ b/mount
@@ -1,4 +1,5 @@
 #!/bin/bash
+sudo apt-get install -y parted 
 
 # 检查是否已经挂载到 /data
 if [ -d "/data" ]; then
@@ -15,14 +16,19 @@ if [ -z "$disk" ]; then
 fi
 
 # 将磁盘分区并格式化为 ext4 文件系统
-parted -s "/dev/$disk" -- mklabel gpt \
-                      mkpart primary ext4 1MiB -1MiB \
-                      set 1 msftdata on
-mkfs.ext4 "/dev/${disk}1"
+if command -v parted >/dev/null; then
+    parted -s "/dev/$disk" -- mklabel gpt \
+                          mkpart primary ext4 1MiB -1MiB \
+                          set 1 msftdata on
+    mkfs.ext4 "/dev/${disk}1"
 
-# 挂载到 /data 目录
-mkdir -p /data
-mount "/dev/${disk}1" /data
+    # 挂载到 /data 目录
+    mkdir -p /data
+    mount "/dev/${disk}1" /data
 
-echo "Hard drive successfully mounted to /data"
-exit 0
+    echo "Hard drive successfully mounted to /data"
+    exit 0
+else
+    echo "Error: parted command not found"
+    exit 1
+fi
